In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import LSTM, Dense
import matplotlib.pyplot as plt
import math
from sklearn.metrics import mean_squared_error
import datetime

# Load data
def load_data():
    url = "BTC_99.csv"  # replace with the path to your data
    data = pd.read_csv(url)
    data['datetime'] = pd.to_datetime(data['date'])
    data = data.loc[data['datetime'] >= pd.to_datetime('2023-01-01', utc=True)]
    data = data[['datetime', 'close']]  # replace 'close' with the name of your close price column
    return data

# Create dataset
def create_dataset(dataset, look_back=1):
    dataX, dataY = [], []
    for i in range(len(dataset) - look_back - 1):
        a = dataset[i:(i + look_back), 0]
        dataX.append(a)
        dataY.append(dataset[i + look_back, 0])
    return np.array(dataX), np.array(dataY)

# Train model
def train_model(data):
    dataset = data.values
    dataset = dataset.astype('float32')
    
    # Normalize the dataset
    scaler = MinMaxScaler(feature_range=(0, 1))
    dataset = scaler.fit_transform(dataset)
    
    # Split into train and test sets
    train_size = int(len(dataset) * 0.67)
    test_size = len(dataset) - train_size
    train, test = dataset[0:train_size, :], dataset[train_size:len(dataset), :]
    
    # Prepare the dataset
    look_back = 20  # Increased look_back
    trainX, trainY = create_dataset(train, look_back)
    testX, testY = create_dataset(test, look_back)
    
    # Reshape input to be [samples, time steps, features]
    trainX = np.reshape(trainX, (trainX.shape[0], 1, trainX.shape[1]))
    testX = np.reshape(testX, (testX.shape[0], 1, testX.shape[1]))
    
    # Create and fit the LSTM network
    model = Sequential()
    model.add(LSTM(4, input_shape=(1, look_back)))
    model.add(Dense(1))
    model.compile(loss='mean_squared_error', optimizer='adam')
    model.fit(trainX, trainY, epochs=100, batch_size=256, verbose=2)
    
    # Make predictions
    trainPredict = model.predict(trainX)
    testPredict = model.predict(testX)
    
    # Invert predictions and targets to unscaled
    trainPredict = scaler.inverse_transform(trainPredict)
    trainY = scaler.inverse_transform([trainY])
    testPredict = scaler.inverse_transform(testPredict)
    testY = scaler.inverse_transform([testY])
    
    # Calculate root mean squared error
    trainScore = math.sqrt(mean_squared_error(trainY[0], trainPredict[:,0]))
    print('Train Score: %.2f RMSE' % (trainScore))
    testScore = math.sqrt(mean_squared_error(testY[0], testPredict[:,0]))
    print('Test Score: %.2f RMSE' % (testScore))
    
    return model, scaler

# Main function to train the model and make predictions
def main():
    data = load_data()
    while True:
        current_time = datetime.datetime.now()
        if current_time.minute == 0:  # Retrain and predict every hour
            model, scaler = train_model(data)
            # Add your prediction and plotting code here...
            data = load_data()  # Update the data

main()

In [2]:
from okx_api import Market
from pprint import pprint

if __name__ == '__main__':
    market = Market()
    result = market.get_history_index_candles(instId='BTC-USD', bar='1D', limit='100')
    if result:
        pprint(result)
    else:
        print("Failed to fetch historical data.")

{'code': '0',
 'data': [['1696780800000', '27910.8', '27996.2', '27395.5', '27451.7', '1'],
          ['1696694400000', '27956.2', '28102.7', '27715.7', '27910.7', '1'],
          ['1696608000000', '27953.7', '28276.7', '27809.8', '27956.1', '1'],
          ['1696521600000', '27561.3', '28052.7', '27191.3', '27953.8', '1'],
          ['1696435200000', '27401.6', '28118.6', '27399.1', '27561.1', '1'],
          ['1696348800000', '27346.4', '27637.6', '27178.9', '27402.1', '1'],
          ['1696262400000', '28056.7', '28134.3', '27251.6', '27346.4', '1'],
          ['1696176000000', '27151.7', '28590.2', '27049.2', '28056.6', '1'],
          ['1696089600000', '27004.4', '27285.5', '26962.6', '27151.7', '1'],
          ['1696003200000', '26889', '27096.1', '26760.9', '27004.3', '1'],
          ['1695916800000', '27012.3', '27302.3', '26690.4', '26889', '1'],
          ['1695830400000', '26290.2', '27037.6', '26107.3', '27011.1', '1'],
          ['1695744000000', '26125.8', '26830.6', '26105.8', '26289.4', '1'],
          ['1695657600000', '26243.6', '26437.9', '26096.9', '26126', '1'],
          ['1695571200000', '26583.2', '26732.8', '26005.7', '26243.3', '1'],
          ['1695484800000', '26579.4', '26639.4', '26556.8', '26583.2', '1'],
          ['1695398400000', '26643.8', '26650.3', '26505.5', '26579.8', '1'],
          ['1695312000000', '26588.8', '26733.9', '26489.1', '26643.7', '1'],
          ['1695225600000', '27189.6', '27296.7', '26382.4', '26589', '1'],
          ['1695139200000', '27432.7', '27491.5', '26954.2', '27189.6', '1'],
          ['1695052800000', '27284.7', '27490.3', '26650.9', '27431.7', '1'],
          ['1694966400000', '26561.6', '27425', '26411.2', '27284.5', '1'],
          ['1694880000000', '26520.8', '26621.7', '26439.6', '26561.4', '1'],
          ['1694793600000', '26324.5', '26883.8', '26320.7', '26520.8', '1'],
          ['1694707200000', '26706.6', '26844.3', '26231.4', '26324.3', '1'],
          ['1694620800000', '26257.2', '26796.5', '26069.6', '26706', '1'],
          ['1694534400000', '26210.7', '26532.9', '25775.2', '26257.2', '1'],
          ['1694448000000', '25109.5', '26384.7', '24920.9', '26210.5', '1'],
          ['1694361600000', '25775.1', '26019.3', '24959.7', '25109.9', '1'],
          ['1694275200000', '25891.2', '25934.9', '25721.9', '25774.7', '1'],
          ['1694188800000', '25840.1', '25929.7', '25729.5', '25891.2', '1'],
          ['1694102400000', '25769.8', '26432.4', '25659.3', '25840.1', '1'],
          ['1694016000000', '25589.5', '26018.3', '25390.5', '25770.3', '1'],
          ['1693929600000', '25748.8', '25850.7', '25543.5', '25589.5', '1'],
          ['1693843200000', '25808.6', '25935', '25571.7', '25748.8', '1'],
          ['1693756800000', '25871.6', '26120.5', '25727.9', '25808.6', '1'],
          ['1693670400000', '25903.7', '26066.9', '25766.8', '25871.2', '1'],
          ['1693584000000', '25803.2', '25980.3', '25333.4', '25903.6', '1'],
          ['1693497600000', '26923.9', '26924.6', '25581.3', '25803.2', '1'],
          ['1693411200000', '27208.8', '27538.6', '26817.2', '26923.9', '1'],
          ['1693324800000', '27426.5', '28149.5', '27038.2', '27208.7', '1'],
          ['1693238400000', '26090.7', '27722.7', '25922.5', '27426.5', '1'],
          ['1693152000000', '26118.2', '26234.7', '25866.1', '26090.5', '1'],
          ['1693065600000', '26050.9', '26170.4', '25973', '26118.1', '1'],
          ['1692979200000', '25929.2', '26111.5', '25829.4', '26050.9', '1'],
          ['1692892800000', '25992.3', '26292.2', '25777.4', '25929.2', '1'],
          ['1692806400000', '26139.6', '26804.4', '25988.3', '25992.5', '1'],
          ['1692720000000', '25932.7', '26173.7', '25368.1', '26139.4', '1'],
          ['1692633600000', '25940.8', '26240.1', '25920.1', '25932.7', '1'],
          ['1692547200000', '26108.6', '26290.4', '25822.9', '25941.4', '1'],
          ['1692460800000', '26214.5', '26263.5', '25985.3', '26108.5', '1'],
          ['1692374400000', '25981.2', '26291.3', '25623.3', '26215.4', '1'],
          ['1692288000000', '27911.1', '28059.3', '25309.1', '25979.8', '1'],
          ['1692201600000', '29082.4', '29205', '27868.3', '27910.6', '1'],
          ['1692115200000', '29299.3', '29333.8', '29030.5', '29082.6', '1'],
          ['1692028800000', '29575.1', '29666', '29242.4', '29299.2', '1'],
          ['1691942400000', '29359.4', '29634.4', '29093.1', '29574.9', '1'],
          ['1691856000000', '29433.4', '29470.3', '29354.6', '29359', '1'],
          ['1691769600000', '29364.3', '29443.3', '29229.3', '29433.3', '1'],
          ['1691683200000', '29447.1', '29535.3', '29321.8', '29364', '1'],
          ['1691596800000', '29751.1', '29764', '29365.3', '29447.4', '1'],
          ['1691510400000', '29520', '30221.9', '29519.1', '29750.9', '1'],
          ['1691424000000', '28829.5', '29652.3', '28673.8', '29520.2', '1'],
          ['1691337600000', '28982.9', '29186.2', '28775.3', '28829.9', '1'],
          ['1691251200000', '29015', '29105.5', '28967.2', '28982.9', '1'],
          ['1691164800000', '29260.9', '29269.7', '28795.6', '29015.1', '1'],
          ['1691078400000', '29237.1', '29345.3', '29098.6', '29260.2', '1'],
          ['1690992000000', '29315.3', '29403', '28931.5', '29237.2', '1'],
          ['1690905600000', '28945.1', '30030', '28857.5', '29315.3', '1'],
          ['1690819200000', '29252.9', '29347.7', '28587.8', '28945.5', '1'],
          ['1690732800000', '29354.1', '29524.5', '29049.7', '29253.2', '1'],
          ['1690646400000', '29304', '29452.6', '29249.9', '29354.1', '1'],
          ['1690560000000', '29394.5', '29409.2', '29205.5', '29304', '1'],
          ['1690473600000', '29302.1', '29531', '29093', '29394.5', '1'],
          ['1690387200000', '29327.9', '29687.4', '29211.3', '29302.1', '1'],
          ['1690300800000', '29194.6', '29407.8', '29112.2', '29328.4', '1'],
          ['1690214400000', '29093', '29339.2', '29008.4', '29194.5', '1'],
          ['1690128000000', '29908.6', '30350.1', '28877.1', '29093.1', '1'],
          ['1690041600000', '29911.3', '29985.3', '29645.6', '29908.6', '1'],
          ['1689955200000', '29872', '30062', '29780.8', '29910.7', '1'],
          ['1689868800000', '29814.8', '29953', '29587.3', '29872', '1'],
          ['1689782400000', '29957', '30419.1', '29635.3', '29814.4', '1'],
          ['1689696000000', '29914.1', '30196.6', '29543.3', '29957', '1'],
          ['1689609600000', '30187', '30288', '29676.8', '29914.3', '1'],
          ['1689523200000', '30396.1', '30419.8', '30001.3', '30186.9', '1'],
          ['1689436800000', '30318.6', '30454.6', '30081', '30396.1', '1'],
          ['1689350400000', '31256', '31287', '29937.8', '30318.7', '1'],
          ['1689264000000', '30925.6', '31828.2', '30742.9', '31256', '1'],
          ['1689177600000', '30518.2', '31185.9', '30227.4', '30925.1', '1'],
          ['1689091200000', '30601.8', '30974.7', '30426.1', '30518.2', '1'],
          ['1689004800000', '30317.8', '31040.9', '30213.5', '30601.8', '1'],
          ['1688918400000', '30363.4', '30363.4', '29965.9', '30317.8', '1'],
          ['1688832000000', '30220.1', '30445.2', '30064.2', '30362.3', '1'],
          ['1688745600000', '30403.7', '30448.3', '30133.9', '30220.1', '1'],
          ['1688659200000', '30419.9', '30465.8', '29726.7', '30403.9', '1'],
          ['1688572800000', '30360.5', '31520', '29907.6', '30419.1', '1'],
          ['1688486400000', '30965.4', '31128.4', '30207.1', '30359.8', '1'],
          ['1688400000000', '31065.8', '31385.9', '30846.7', '30965.5', '1'],
          ['1688313600000', '30503', '31168.3', '30383.6', '31065.8', '1'],
          ['1688227200000', '30578.9', '30648.8', '30188.7', '30503.1', '1']],
 'msg': ''}

In [3]:
result['data']

[['1696780800000', '27910.8', '27996.2', '27395.5', '27451.7', '1'],
 ['1696694400000', '27956.2', '28102.7', '27715.7', '27910.7', '1'],
 ['1696608000000', '27953.7', '28276.7', '27809.8', '27956.1', '1'],
 ['1696521600000', '27561.3', '28052.7', '27191.3', '27953.8', '1'],
 ['1696435200000', '27401.6', '28118.6', '27399.1', '27561.1', '1'],
 ['1696348800000', '27346.4', '27637.6', '27178.9', '27402.1', '1'],
 ['1696262400000', '28056.7', '28134.3', '27251.6', '27346.4', '1'],
 ['1696176000000', '27151.7', '28590.2', '27049.2', '28056.6', '1'],
 ['1696089600000', '27004.4', '27285.5', '26962.6', '27151.7', '1'],
 ['1696003200000', '26889', '27096.1', '26760.9', '27004.3', '1'],
 ['1695916800000', '27012.3', '27302.3', '26690.4', '26889', '1'],
 ['1695830400000', '26290.2', '27037.6', '26107.3', '27011.1', '1'],
 ['1695744000000', '26125.8', '26830.6', '26105.8', '26289.4', '1'],
 ['1695657600000', '26243.6', '26437.9', '26096.9', '26126', '1'],
 ['1695571200000', '26583.2', '26732.8', '26005.7', '26243.3', '1'],
 ['1695484800000', '26579.4', '26639.4', '26556.8', '26583.2', '1'],
 ['1695398400000', '26643.8', '26650.3', '26505.5', '26579.8', '1'],
 ['1695312000000', '26588.8', '26733.9', '26489.1', '26643.7', '1'],
 ['1695225600000', '27189.6', '27296.7', '26382.4', '26589', '1'],
 ['1695139200000', '27432.7', '27491.5', '26954.2', '27189.6', '1'],
 ['1695052800000', '27284.7', '27490.3', '26650.9', '27431.7', '1'],
 ['1694966400000', '26561.6', '27425', '26411.2', '27284.5', '1'],
 ['1694880000000', '26520.8', '26621.7', '26439.6', '26561.4', '1'],
 ['1694793600000', '26324.5', '26883.8', '26320.7', '26520.8', '1'],
 ['1694707200000', '26706.6', '26844.3', '26231.4', '26324.3', '1'],
 ['1694620800000', '26257.2', '26796.5', '26069.6', '26706', '1'],
 ['1694534400000', '26210.7', '26532.9', '25775.2', '26257.2', '1'],
 ['1694448000000', '25109.5', '26384.7', '24920.9', '26210.5', '1'],
 ['1694361600000', '25775.1', '26019.3', '24959.7', '25109.9', '1'],
 ['1694275200000', '25891.2', '25934.9', '25721.9', '25774.7', '1'],
 ['1694188800000', '25840.1', '25929.7', '25729.5', '25891.2', '1'],
 ['1694102400000', '25769.8', '26432.4', '25659.3', '25840.1', '1'],
 ['1694016000000', '25589.5', '26018.3', '25390.5', '25770.3', '1'],
 ['1693929600000', '25748.8', '25850.7', '25543.5', '25589.5', '1'],
 ['1693843200000', '25808.6', '25935', '25571.7', '25748.8', '1'],
 ['1693756800000', '25871.6', '26120.5', '25727.9', '25808.6', '1'],
 ['1693670400000', '25903.7', '26066.9', '25766.8', '25871.2', '1'],
 ['1693584000000', '25803.2', '25980.3', '25333.4', '25903.6', '1'],
 ['1693497600000', '26923.9', '26924.6', '25581.3', '25803.2', '1'],
 ['1693411200000', '27208.8', '27538.6', '26817.2', '26923.9', '1'],
 ['1693324800000', '27426.5', '28149.5', '27038.2', '27208.7', '1'],
 ['1693238400000', '26090.7', '27722.7', '25922.5', '27426.5', '1'],
 ['1693152000000', '26118.2', '26234.7', '25866.1', '26090.5', '1'],
 ['1693065600000', '26050.9', '26170.4', '25973', '26118.1', '1'],
 ['1692979200000', '25929.2', '26111.5', '25829.4', '26050.9', '1'],
 ['1692892800000', '25992.3', '26292.2', '25777.4', '25929.2', '1'],
 ['1692806400000', '26139.6', '26804.4', '25988.3', '25992.5', '1'],
 ['1692720000000', '25932.7', '26173.7', '25368.1', '26139.4', '1'],
 ['1692633600000', '25940.8', '26240.1', '25920.1', '25932.7', '1'],
 ['1692547200000', '26108.6', '26290.4', '25822.9', '25941.4', '1'],
 ['1692460800000', '26214.5', '26263.5', '25985.3', '26108.5', '1'],
 ['1692374400000', '25981.2', '26291.3', '25623.3', '26215.4', '1'],
 ['1692288000000', '27911.1', '28059.3', '25309.1', '25979.8', '1'],
 ['1692201600000', '29082.4', '29205', '27868.3', '27910.6', '1'],
 ['1692115200000', '29299.3', '29333.8', '29030.5', '29082.6', '1'],
 ['1692028800000', '29575.1', '29666', '29242.4', '29299.2', '1'],
 ['1691942400000', '29359.4', '29634.4', '29093.1', '29574.9', '1'],
 ['1691856000000', '29433.4', '29470.3', '29354.6', '29359', '1'],
 ['1691769600000', '29364.3', '29443.3', '29229.3', '29433.3', '1'],
 ['1691683200000', '29447.1', '29535.3', '29321.8', '29364', '1'],
 ['1691596800000', '29751.1', '29764', '29365.3', '29447.4', '1'],
 ['1691510400000', '29520', '30221.9', '29519.1', '29750.9', '1'],
 ['1691424000000', '28829.5', '29652.3', '28673.8', '29520.2', '1'],
 ['1691337600000', '28982.9', '29186.2', '28775.3', '28829.9', '1'],
 ['1691251200000', '29015', '29105.5', '28967.2', '28982.9', '1'],
 ['1691164800000', '29260.9', '29269.7', '28795.6', '29015.1', '1'],
 ['1691078400000', '29237.1', '29345.3', '29098.6', '29260.2', '1'],
 ['1690992000000', '29315.3', '29403', '28931.5', '29237.2', '1'],
 ['1690905600000', '28945.1', '30030', '28857.5', '29315.3', '1'],
 ['1690819200000', '29252.9', '29347.7', '28587.8', '28945.5', '1'],
 ['1690732800000', '29354.1', '29524.5', '29049.7', '29253.2', '1'],
 ['1690646400000', '29304', '29452.6', '29249.9', '29354.1', '1'],
 ['1690560000000', '29394.5', '29409.2', '29205.5', '29304', '1'],
 ['1690473600000', '29302.1', '29531', '29093', '29394.5', '1'],
 ['1690387200000', '29327.9', '29687.4', '29211.3', '29302.1', '1'],
 ['1690300800000', '29194.6', '29407.8', '29112.2', '29328.4', '1'],
 ['1690214400000', '29093', '29339.2', '29008.4', '29194.5', '1'],
 ['1690128000000', '29908.6', '30350.1', '28877.1', '29093.1', '1'],
 ['1690041600000', '29911.3', '29985.3', '29645.6', '29908.6', '1'],
 ['1689955200000', '29872', '30062', '29780.8', '29910.7', '1'],
 ['1689868800000', '29814.8', '29953', '29587.3', '29872', '1'],
 ['1689782400000', '29957', '30419.1', '29635.3', '29814.4', '1'],
 ['1689696000000', '29914.1', '30196.6', '29543.3', '29957', '1'],
 ['1689609600000', '30187', '30288', '29676.8', '29914.3', '1'],
 ['1689523200000', '30396.1', '30419.8', '30001.3', '30186.9', '1'],
 ['1689436800000', '30318.6', '30454.6', '30081', '30396.1', '1'],
 ['1689350400000', '31256', '31287', '29937.8', '30318.7', '1'],
 ['1689264000000', '30925.6', '31828.2', '30742.9', '31256', '1'],
 ['1689177600000', '30518.2', '31185.9', '30227.4', '30925.1', '1'],
 ['1689091200000', '30601.8', '30974.7', '30426.1', '30518.2', '1'],
 ['1689004800000', '30317.8', '31040.9', '30213.5', '30601.8', '1'],
 ['1688918400000', '30363.4', '30363.4', '29965.9', '30317.8', '1'],
 ['1688832000000', '30220.1', '30445.2', '30064.2', '30362.3', '1'],
 ['1688745600000', '30403.7', '30448.3', '30133.9', '30220.1', '1'],
 ['1688659200000', '30419.9', '30465.8', '29726.7', '30403.9', '1'],
 ['1688572800000', '30360.5', '31520', '29907.6', '30419.1', '1'],
 ['1688486400000', '30965.4', '31128.4', '30207.1', '30359.8', '1'],
 ['1688400000000', '31065.8', '31385.9', '30846.7', '30965.5', '1'],
 ['1688313600000', '30503', '31168.3', '30383.6', '31065.8', '1'],
 ['1688227200000', '30578.9', '30648.8', '30188.7', '30503.1', '1']]

In [11]:
import pandas as pd

result

# Extracting the 'data' key from the dictionary
raw_data = result['data']

# Convert the data into a DataFrame
df = pd.DataFrame(raw_data, columns=['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume'])
df = df[['Timestamp', 'Open', 'High', 'Low', 'Close']]
# Ensure that the 'Timestamp' column is of integer type before converting to datetime
df['Timestamp'] = df['Timestamp'].astype(int)
# Convert the timestamp to a datetime format (assuming the timestamp is in milliseconds)
df['Timestamp'] = pd.to_datetime(df['Timestamp'], unit='ms')

print(df.head())  # Display the first few rows of the dataframe

            Timestamp     Open     High      Low    Close
0 2023-10-08 16:00:00  27910.8  27996.2  27395.5  27451.7
1 2023-10-07 16:00:00  27956.2  28102.7  27715.7  27910.7
2 2023-10-06 16:00:00  27953.7  28276.7  27809.8  27956.1
3 2023-10-05 16:00:00  27561.3  28052.7  27191.3  27953.8
4 2023-10-04 16:00:00  27401.6  28118.6  27399.1  27561.1

In [12]:
display(df)

             Timestamp     Open     High      Low    Close
0  2023-10-08 16:00:00  27910.8  27996.2  27395.5  27451.7
1  2023-10-07 16:00:00  27956.2  28102.7  27715.7  27910.7
2  2023-10-06 16:00:00  27953.7  28276.7  27809.8  27956.1
3  2023-10-05 16:00:00  27561.3  28052.7  27191.3  27953.8
4  2023-10-04 16:00:00  27401.6  28118.6  27399.1  27561.1
..                 ...      ...      ...      ...      ...
95 2023-07-05 16:00:00  30360.5    31520  29907.6  30419.1
96 2023-07-04 16:00:00  30965.4  31128.4  30207.1  30359.8
97 2023-07-03 16:00:00  31065.8  31385.9  30846.7  30965.5
98 2023-07-02 16:00:00    30503  31168.3  30383.6  31065.8
99 2023-07-01 16:00:00  30578.9  30648.8  30188.7  30503.1

[100 rows x 5 columns]

In [21]:
from datetime import datetime

# Convert the string into a datetime object
dt = datetime.strptime("20230901 0:00", "%Y%m%d %H:%M")

# Convert datetime object to timestamp in milliseconds
timestamp_milliseconds = int(dt.timestamp() * 1000)

print(timestamp_milliseconds)

1693497600000

In [22]:
from okx_api import Market
from pprint import pprint

if __name__ == '__main__':
    market = Market()
    
    # Define the timestamp you want to fetch data before
    # This timestamp should be in milliseconds since that's how timestamps are typically represented in these APIs.
    timestamp_before = timestamp_milliseconds
    
    result = market.get_history_index_candles(instId='BTC-USD', bar='1D', limit='100', before=timestamp_before)
    
    if result:
        display(result)
    else:
        print("Failed to fetch historical data.")

{'code': '0',
 'msg': '',
 'data': [['1696780800000', '27910.8', '27996.2', '27395.5', '27451.7', '1'],
  ['1696694400000', '27956.2', '28102.7', '27715.7', '27910.7', '1'],
  ['1696608000000', '27953.7', '28276.7', '27809.8', '27956.1', '1'],
  ['1696521600000', '27561.3', '28052.7', '27191.3', '27953.8', '1'],
  ['1696435200000', '27401.6', '28118.6', '27399.1', '27561.1', '1'],
  ['1696348800000', '27346.4', '27637.6', '27178.9', '27402.1', '1'],
  ['1696262400000', '28056.7', '28134.3', '27251.6', '27346.4', '1'],
  ['1696176000000', '27151.7', '28590.2', '27049.2', '28056.6', '1'],
  ['1696089600000', '27004.4', '27285.5', '26962.6', '27151.7', '1'],
  ['1696003200000', '26889', '27096.1', '26760.9', '27004.3', '1'],
  ['1695916800000', '27012.3', '27302.3', '26690.4', '26889', '1'],
  ['1695830400000', '26290.2', '27037.6', '26107.3', '27011.1', '1'],
  ['1695744000000', '26125.8', '26830.6', '26105.8', '26289.4', '1'],
  ['1695657600000', '26243.6', '26437.9', '26096.9', '26126', '1'],
  ['1695571200000', '26583.2', '26732.8', '26005.7', '26243.3', '1'],
  ['1695484800000', '26579.4', '26639.4', '26556.8', '26583.2', '1'],
  ['1695398400000', '26643.8', '26650.3', '26505.5', '26579.8', '1'],
  ['1695312000000', '26588.8', '26733.9', '26489.1', '26643.7', '1'],
  ['1695225600000', '27189.6', '27296.7', '26382.4', '26589', '1'],
  ['1695139200000', '27432.7', '27491.5', '26954.2', '27189.6', '1'],
  ['1695052800000', '27284.7', '27490.3', '26650.9', '27431.7', '1'],
  ['1694966400000', '26561.6', '27425', '26411.2', '27284.5', '1'],
  ['1694880000000', '26520.8', '26621.7', '26439.6', '26561.4', '1'],
  ['1694793600000', '26324.5', '26883.8', '26320.7', '26520.8', '1'],
  ['1694707200000', '26706.6', '26844.3', '26231.4', '26324.3', '1'],
  ['1694620800000', '26257.2', '26796.5', '26069.6', '26706', '1'],
  ['1694534400000', '26210.7', '26532.9', '25775.2', '26257.2', '1'],
  ['1694448000000', '25109.5', '26384.7', '24920.9', '26210.5', '1'],
  ['1694361600000', '25775.1', '26019.3', '24959.7', '25109.9', '1'],
  ['1694275200000', '25891.2', '25934.9', '25721.9', '25774.7', '1'],
  ['1694188800000', '25840.1', '25929.7', '25729.5', '25891.2', '1'],
  ['1694102400000', '25769.8', '26432.4', '25659.3', '25840.1', '1'],
  ['1694016000000', '25589.5', '26018.3', '25390.5', '25770.3', '1'],
  ['1693929600000', '25748.8', '25850.7', '25543.5', '25589.5', '1'],
  ['1693843200000', '25808.6', '25935', '25571.7', '25748.8', '1'],
  ['1693756800000', '25871.6', '26120.5', '25727.9', '25808.6', '1'],
  ['1693670400000', '25903.7', '26066.9', '25766.8', '25871.2', '1'],
  ['1693584000000', '25803.2', '25980.3', '25333.4', '25903.6', '1']]}

             Timestamp     Open     High      Low    Close
0  2023-10-08 16:00:00  27910.8  27996.2  27395.5  27451.7
1  2023-10-07 16:00:00  27956.2  28102.7  27715.7  27910.7
2  2023-10-06 16:00:00  27953.7  28276.7  27809.8  27956.1
3  2023-10-05 16:00:00  27561.3  28052.7  27191.3  27953.8
4  2023-10-04 16:00:00  27401.6  28118.6  27399.1  27561.1
5  2023-10-03 16:00:00  27346.4  27637.6  27178.9  27402.1
6  2023-10-02 16:00:00  28056.7  28134.3  27251.6  27346.4
7  2023-10-01 16:00:00  27151.7  28590.2  27049.2  28056.6
8  2023-09-30 16:00:00  27004.4  27285.5  26962.6  27151.7
9  2023-09-29 16:00:00    26889  27096.1  26760.9  27004.3
10 2023-09-28 16:00:00  27012.3  27302.3  26690.4    26889
11 2023-09-27 16:00:00  26290.2  27037.6  26107.3  27011.1
12 2023-09-26 16:00:00  26125.8  26830.6  26105.8  26289.4
13 2023-09-25 16:00:00  26243.6  26437.9  26096.9    26126
14 2023-09-24 16:00:00  26583.2  26732.8  26005.7  26243.3
15 2023-09-23 16:00:00  26579.4  26639.4  26556.8  26583.2
16 2023-09-22 16:00:00  26643.8  26650.3  26505.5  26579.8
17 2023-09-21 16:00:00  26588.8  26733.9  26489.1  26643.7
18 2023-09-20 16:00:00  27189.6  27296.7  26382.4    26589
19 2023-09-19 16:00:00  27432.7  27491.5  26954.2  27189.6
20 2023-09-18 16:00:00  27284.7  27490.3  26650.9  27431.7
21 2023-09-17 16:00:00  26561.6    27425  26411.2  27284.5
22 2023-09-16 16:00:00  26520.8  26621.7  26439.6  26561.4
23 2023-09-15 16:00:00  26324.5  26883.8  26320.7  26520.8
24 2023-09-14 16:00:00  26706.6  26844.3  26231.4  26324.3
25 2023-09-13 16:00:00  26257.2  26796.5  26069.6    26706
26 2023-09-12 16:00:00  26210.7  26532.9  25775.2  26257.2
27 2023-09-11 16:00:00  25109.5  26384.7  24920.9  26210.5
28 2023-09-10 16:00:00  25775.1  26019.3  24959.7  25109.9
29 2023-09-09 16:00:00  25891.2  25934.9  25721.9  25774.7
30 2023-09-08 16:00:00  25840.1  25929.7  25729.5  25891.2
31 2023-09-07 16:00:00  25769.8  26432.4  25659.3  25840.1
32 2023-09-06 16:00:00  25589.5  26018.3  25390.5  25770.3
33 2023-09-05 16:00:00  25748.8  25850.7  25543.5  25589.5
34 2023-09-04 16:00:00  25808.6    25935  25571.7  25748.8
35 2023-09-03 16:00:00  25871.6  26120.5  25727.9  25808.6
36 2023-09-02 16:00:00  25903.7  26066.9  25766.8  25871.2
37 2023-09-01 16:00:00  25803.2  25980.3  25333.4  25903.6

In [ ]:
from okx_api import Market
import pandas as pd
import logging
from tqdm import tqdm
import time

# Set up the logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def convert_to_dataframe(result):
    # Convert the data into a DataFrame
    df = pd.DataFrame(result, columns=['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume'])
    df = df[['Timestamp', 'Open', 'High', 'Low', 'Close']]
    # Ensure that the 'Timestamp' column is of integer type before converting to datetime
    df['Timestamp'] = df['Timestamp'].astype(int)
    # Convert the timestamp to a datetime format (assuming the timestamp is in milliseconds)
    df['Timestamp'] = pd.to_datetime(df['Timestamp'], unit='ms')
    display(df)
    return df
    
def date_to_timestamp(date_str):
    """Convert a date string to a timestamp."""
    return int(pd.Timestamp(date_str).timestamp() * 1000)

def fetch_data_between_dates(instId, start_date, end_date, bar='1D', limit=100):
    """Fetch historical data between start_date and end_date."""
    
    market = Market()
    all_data = []
    
    # Convert start_date to timestamp
    before_timestamp = date_to_timestamp(end_date)
    
    # Convert end_date to timestamp
    start_timestamp = date_to_timestamp(start_date)
    bar_to_milliseconds = {
        '1D': 86400000,
        '1H': 3600000,
        '1M': 86400000 * 30  # Approximation, assuming 30 days in a month
        # ... add other intervals as needed
    }
    
    interval_milliseconds = bar_to_milliseconds[bar]
    logger.info(f"Fetching data from {start_date} to {end_date}...")
    
    # We'll use a while loop, but we don't know the exact number of iterations.
    # Let's use a dummy tqdm loop to update the progress bar manually.
    with tqdm(total=100, desc="Fetching data", dynamic_ncols=True) as pbar:
        previous_length = 0
        consecutive_failures = 0
        MAX_CONSECUTIVE_FAILURES = 5  # You can adjust this as needed
        while True:
            # Fetch a batch of data
            result = market.get_history_index_candles(instId=instId, bar=bar, limit=str(limit), before=str(before_timestamp))
            
            # If no data fetched, try a previous time interval
            if not result or 'data' not in result or not result['data']:
                consecutive_failures += 1
                if consecutive_failures >= MAX_CONSECUTIVE_FAILURES:
                    print("Reached maximum number of consecutive failed attempts. Exiting.")
                    break
                before_timestamp -= interval_milliseconds
                print(f"Data fetching failed for timestamp {before_timestamp}. Retrying with previous timestamp.")
                continue

            # Reset consecutive failures count if we successfully fetched data
            consecutive_failures = 0
                
            # Add the fetched data to all_data
            all_data.extend(result['data'])
            
            # Update the before_timestamp with the timestamp of the earliest data point in the fetched batch
            earliest_timestamp = int(result['data'][-1][0])
            
            # If earliest_timestamp is later than start_timestamp, break out of the loop
            if earliest_timestamp <= start_timestamp:
                print("earliest_timestamp smaller than start_timestamp, exit")
                break
            
            before_timestamp = earliest_timestamp
            
            # Update tqdm progress bar based on the new data fetched
            new_data_length = len(all_data) - previous_length
            pbar.update(new_data_length / limit * 100)
            previous_length = len(all_data)
            
            # Sleep for a short duration to avoid hitting rate limits (if any)
            time.sleep(2)
    
    logger.info("Data fetching complete!")
    
    # Filter out the data which is after the start_date
    all_data = [data for data in all_data if int(data[0]) >= start_timestamp]
    
    return all_data


# Example usage:
if __name__ == '__main__':
    data = fetch_data_between_dates('BTC-USD', '2023-01-01', '2023-10-08')
    print(data)
    result = convert_to_dataframe(data)
    result.to_csv("a.csv",index = True)

INFO:__main__:Fetching data from 2023-01-01 to 2023-10-08...
Fetching data:   1%|▎                         | 1.0/100 [00:02<03:35,  2.17s/it]

Data fetching failed for timestamp 1696694400000. Retrying with previous timestamp.

Fetching data:   2%|▌                         | 2.0/100 [00:06<05:41,  3.49s/it]

Data fetching failed for timestamp 1696694400000. Retrying with previous timestamp.

Fetching data:   3%|▊                         | 3.0/100 [00:12<07:17,  4.51s/it]

Data fetching failed for timestamp 1696694400000. Retrying with previous timestamp.

Fetching data:   4%|█                         | 4.0/100 [00:17<07:19,  4.58s/it]

Data fetching failed for timestamp 1696694400000. Retrying with previous timestamp.

Fetching data:   5%|█▎                        | 5.0/100 [00:21<07:07,  4.50s/it]

Data fetching failed for timestamp 1696694400000. Retrying with previous timestamp.

Fetching data:   6%|█▌                        | 6.0/100 [00:26<07:07,  4.55s/it]

Data fetching failed for timestamp 1696694400000. Retrying with previous timestamp.

Fetching data:   7%|█▊                        | 7.0/100 [00:30<07:14,  4.67s/it]

Data fetching failed for timestamp 1696694400000. Retrying with previous timestamp.

Fetching data:   8%|██                        | 8.0/100 [00:35<07:11,  4.69s/it]

Data fetching failed for timestamp 1696694400000. Retrying with previous timestamp.

Fetching data:   9%|██▎                       | 9.0/100 [00:40<07:22,  4.86s/it]

Data fetching failed for timestamp 1696694400000. Retrying with previous timestamp.

Fetching data:  10%|██▌                      | 10.0/100 [00:46<07:42,  5.14s/it]

Data fetching failed for timestamp 1696694400000. Retrying with previous timestamp.